// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	coins "aprian1337/thukul-service/business/coins"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CoinsCreateSymbol provides a mock function with given fields: ctx, domain
func (_m *Repository) CoinsCreateSymbol(ctx context.Context, domain coins.Domain) (coins.Domain, error) {
	ret := _m.Called(ctx, domain)

	var r0 coins.Domain
	if rf, ok := ret.Get(0).(func(context.Context, coins.Domain) coins.Domain); ok {
		r0 = rf(ctx, domain)
	} else {
		r0 = ret.Get(0).(coins.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, coins.Domain) error); ok {
		r1 = rf(ctx, domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CoinsGetSymbol provides a mock function with given fields: ctx, symbol
func (_m *Repository) CoinsGetSymbol(ctx context.Context, symbol string) (coins.Domain, int64, error) {
	ret := _m.Called(ctx, symbol)

	var r0 coins.Domain
	if rf, ok := ret.Get(0).(func(context.Context, string) coins.Domain); ok {
		r0 = rf(ctx, symbol)
	} else {
		r0 = ret.Get(0).(coins.Domain)
	}

	var r1 int64
	if rf, ok := ret.Get(1).(func(context.Context, string) int64); ok {
		r1 = rf(ctx, symbol)
	} else {
		r1 = ret.Get(1).(int64)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, symbol)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetAllSymbol provides a mock function with given fields: ctx
func (_m *Repository) GetAllSymbol(ctx context.Context) ([]coins.Domain, error) {
	ret := _m.Called(ctx)

	var r0 []coins.Domain
	if rf, ok := ret.Get(0).(func(context.Context) []coins.Domain); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]coins.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
