// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	coins "aprian1337/thukul-service/business/coins"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// GetBySymbol provides a mock function with given fields: ctx, symbol
func (_m *Usecase) GetBySymbol(ctx context.Context, symbol string) (coins.Domain, error) {
	ret := _m.Called(ctx, symbol)

	var r0 coins.Domain
	if rf, ok := ret.Get(0).(func(context.Context, string) coins.Domain); ok {
		r0 = rf(ctx, symbol)
	} else {
		r0 = ret.Get(0).(coins.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, symbol)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
